apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8spod2nfs
  labels:
    app: k8spod2nfs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8spod2nfs
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: k8spod2nfs
    spec:
      containers:
      - image: scottsbaldwin/docker-hello-world:latest
        ports:
        - containerPort: 80
          name: k8spod2nfs
        imagePullPolicy: IfNotPresent
        name: k8snfspod
        volumeMounts:
          - name: nfs
            mountPath: "/usr/share/nginx/html"
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
---
apiVersion: v1
kind: Service
metadata:
  name: k8spod2nfs
spec:
 type: LoadBalancer
 selector:
  app: k8spod2nfs
 ports:
   - name: client
     protocol: TCP
     port: 80
